spring:
  profiles:
    active: develop
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://host:port/boot
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true